name: Build and Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        build_type: [debug, release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: cmake --preset=ninja-multi

      - name: Build
        run: cmake --build --preset=ninja-${{ matrix.build_type }}

      - name: Run Tests
        run: ctest --preset=test-${{ matrix.build_type }}

      - name: Copy data.json to execution directory
        run: |
          cp test/data.json ./bin/${{ matrix.build_type }}/
        shell: bash

      - name: Debug — list bin directory
        run: ls -R ./bin/
        shell: bash

      - name: Debug — list full working directory
        run: ls -R
        shell: bash

      - name: Run test-data and save output
        run: |
          cd ./bin/${{ matrix.build_type }}/
          ./test.exe --test-data > test-data-output-${{ matrix.build_type }}.txt
        shell: bash

      - name: Upload test data output
        uses: actions/upload-artifact@v4
        with:
          name: test-data-output-${{ matrix.build_type }}
          path: bin/${{ matrix.build_type }}/test-data-output-${{ matrix.build_type }}.txt
